src/Entity/Medecin.php
<?php

namespace App\Entity;

use Symfony\Component\Validator\Constraints as Assert;
use App\Repository\MedecinRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: MedecinRepository::class)]
class Medecin implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[Assert\NotBlank(message:"username must not be blank")]
    /**
 * @Assert\Regex(
 *     pattern="/^[a-zA-Z ]+$/",
 *     message="Please enter a value containing only letters and spaces."
 * )
 */
    #[ORM\Column(length: 30)]

    private ?string $username = null;

    #[Assert\NotBlank(message:"email must not be blank")]
    #[Assert\Email(message: "Please enter a valid email address")]
    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[Assert\NotBlank(message:"phone must not be blank")]
    /**
     * @Assert\Regex(
     *     pattern="/^[0-9]+$/",
     *     message="The value '{{ value }}' can only contain numbers."
     * )
     */
    #[ORM\Column(length: 10)]
    private ?string $phone = null;
   
    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    /**
     * @Assert\Length(
     *      min = 6,
     *      minMessage = "Password must be at least {{ limit }} characters long",
     * max=8,
     * maxMessage = "Password must be at least {{ limit }} characters long"
     * )
     */
    private ?string $password = null;


    #[ORM\Column]
    private ?int $token = null;

    #[ORM\Column(length: 254, nullable: true)]
    private ?string $photo = null;

    #[ORM\Column(nullable: true)]
    private ?int $code = null;
    #[ORM\Column]
    private array $role = [];

   
    #[ORM\Column(length: 30)]
   
    private ?string $specialite = null;

    
    
    #[ORM\Column(length: 30)]
   
    private ?string $adress = null;

    
    #[Assert\NotBlank(message:"full name must not be blank")]
   /**
 * @Assert\Regex(
 *     pattern="/^[a-zA-Z ]+$/",
 *     message="Please enter a value containing only letters and spaces."
 * )
 */
    #[ORM\Column(length: 30)]
    private ?string $fullname = null;

    public function __construct()
     {
         $this->token = 1;
     }
 

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    
    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $role = $this->role;
        // guarantee every user at least has ROLE_USER
        $role[] = 'user';

        return array_unique($role);
    }

    public function setRoles(array $role): static
    {
        $this->role = $role;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): static
    {
        $this->username = $username;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): static
    {
        $this->phone = $phone;

        return $this;
    }

    public function getToken(): ?int
    {
        return $this->token;
    }

    public function setToken(int $token): static
    {
        $this->token = $token;

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(?string $photo): static
    {
        $this->photo = $photo;

        return $this;
    }

    public function getSpecialite(): ?string
    {
        return $this->specialite;
    }

    public function setSpecialite(string $specialite): static
    {
        $this->specialite = $specialite;

        return $this;
    }

    public function getAdress(): ?string
    {
        return $this->adress;
    }

    public function setAdress(string $adress): static
    {
        $this->adress = $adress;

        return $this;
    }

    public function getFullname(): ?string
    {
        return $this->fullname;
    }

    public function setFullname(string $fullname): static
    {
        $this->fullname = $fullname;

        return $this;
    }

    public function getCode(): ?int
    {
        return $this->code;
    }

    public function setCode(?int $code): static
    {
        $this->code = $code;

        return $this;
    }
}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\Medecin;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\RepeatedType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('username')
            ->add('fullname')
            ->add('email')
            ->add('phone')
            ->add('password', RepeatedType::class,[
               'type'=>PasswordType::class,
               'first_options'=>['label'=>'Password'] ,
               'second_options'=>['label'=>'Confirm Password']
            ])
            ->add('photo', FileType::class, [
                'label' => 'Profile Picture',
                'mapped' => false,
                'required' => false, // Set to true if the photo is mandatory
                // Add any other options you need, such as validation constraints
            ])
            ->add('Submit',SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Medecin::class,
        ]);
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;
use Dompdf\Options;
use App\Entity\Medecin;
use OpenAI;
use App\Form\DoctorType;
use App\Form\UserType;
use App\Repository\MedecinRepository;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\Persistence\ManagerRegistry;
use Dompdf\Dompdf;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

class UserController extends AbstractController
{
    #[Route('/pagehome', name: 'pagehome')]
    public function index(): Response
    {
        return $this->render('user/pagehome.html.twig', [
            
        ]);
    }



    private $passwordEncoder;//hashage mdp

    public function __construct(UserPasswordEncoderInterface $passwordEncoder)
    {
        $this->passwordEncoder = $passwordEncoder;
    }




    #[Route('/edituser/{id}', name: 'edituser')]
    public function editadmin($id, ManagerRegistry $managerRegistry, Request $req, MedecinRepository $UserRepository, UserPasswordEncoderInterface $passwordEncoder): Response
    {
        $entityManager = $managerRegistry->getManager();
        $detaid = $UserRepository->find($id);
    
        if (!$detaid) {
            throw $this->createNotFoundException('Utilisateur non trouvé');
        }
    
        $form = $this->createForm(UserType::class, $detaid);
        $form->handleRequest($req);
    
        if ($form->isSubmitted() && $form->isValid()) {
            $detaid->setSpecialite(0);
            $detaid->setAdress(0);
            // Hacher le mot de passe
            $photoFile = $form->get('photo')->getData();
    
            if ($photoFile) {
                $newFilename = uniqid().'.'.$photoFile->guessExtension();
    
                try {
                    $photoFile->move(
                        $this->getParameter('photo_directory'), // Specify the directory where photos should be uploaded
                        $newFilename
                    );
                } catch (FileException $e) {
                    // Handle file upload error
                }
    
                // Update the photo path in the user entity
                $detaid->setPhoto($newFilename);
            }
            $detaid = $form->getData();
            $hashedPassword = $passwordEncoder->encodePassword($detaid, $detaid->getPassword());
            $detaid->setPassword($hashedPassword);
    
            $entityManager->persist($detaid);
            $entityManager->flush();
    
            return $this->redirectToRoute('app_login');
        }
    
        return $this->render('user/edituser.html.twig', [
            'form' => $form->createView()
        ]);
    }
    
    
    
    



    
    
    
    #[Route('/editdoc/{id}', name: 'editdoc')]
    public function editdoc($id, ManagerRegistry $managerRegistry, Request $req, MedecinRepository $UserRepository, UserPasswordEncoderInterface $passwordEncoder): Response
    {
        $entityManager = $managerRegistry->getManager();
        $detaid = $UserRepository->find($id);
    
        if (!$detaid) {
            throw $this->createNotFoundException('Utilisateur non trouvé');
        }
    
        $form = $this->createForm(DoctorType::class, $detaid);
        $form->handleRequest($req);
    
        if ($form->isSubmitted() && $form->isValid()) {
            // Hacher le mot de passe
            $photoFile = $form->get('photo')->getData();
    
            if ($photoFile) {
                $newFilename = uniqid().'.'.$photoFile->guessExtension();
    
                try {
                    $photoFile->move(
                        $this->getParameter('photo_directory'), // Specify the directory where photos should be uploaded
                        $newFilename
                    );
                } catch (FileException $e) {
                    // Handle file upload error
                }
    
                // Update the photo path in the user entity
                $detaid->setPhoto($newFilename);
            }
            $detaid = $form->getData();
            $hashedPassword = $passwordEncoder->encodePassword($detaid, $detaid->getPassword());
            $detaid->setPassword($hashedPassword);
    
            $entityManager->persist($detaid);
            $entityManager->flush();
    
            return $this->redirectToRoute('app_login');
        }
    
        return $this->render('user/editdoc.html.twig', [
            'form' => $form->createView()
        ]);
    }
    
    
    
    
    
    
        #[Route('/profile', name: 'profile')]
        public function profile(SessionInterface $session): Response
        {
            // Retrieve user data from the session
            $user = $session->get('user');
    
            // Render the profile page template with user data
            return $this->render('user/profile.html.twig', [
                'user' => $user,
            ]);
        }
    
    
        #[Route('/profiledoc', name: 'profiledoc')]
        public function profiledoc(SessionInterface $session): Response
        {
            // Retrieve user data from the session
            $user = $session->get('user');
    
            // Render the profile page template with user data
            return $this->render('user/profiledoc.html.twig', [
                'user' => $user,
            ]);
        }
    
    
    
    
        #[Route('/showdbuser', name: 'showdbuser')]
        public function showdbuser(MedecinRepository $userRepository): Response
        {
           
            // Fetch user data from the repository
            $users = $userRepository->findAll();
           
            // Pass PDF content and user data to the view
            return $this->render('user/showdbuser.html.twig', [
                'user' => $users,
            ]);
        }

        #[Route('/pdfadmin', name: 'pdfadmin')]
        public function generatePdf(MedecinRepository $userRepository): Response
{
    $dompdf = new Dompdf();

    // Fetch user data from the repository
    $users = $userRepository->findAll();

    // Render HTML content for pdfadmin.html.twig
    $html = $this->renderView('user/pdfadmin.html.twig', [
        'user' => $users,
    ]);

    // Load HTML to Dompdf
    $dompdf->loadHtml($html);

    // Set paper size and orientation
    $dompdf->setPaper('A4', 'portrait');

    // Create options instance
    $options = new Options();

    // Set options
    $options->set('dpi', 150); // Adjust DPI for better image and text quality
    $options->set('isHtml5ParserEnabled', true); // Enable HTML5 parser
    // Add more options as needed

    // Apply options to Dompdf
    $dompdf->setOptions($options);

    // Render PDF
    $dompdf->render();

    // Get PDF content
    $pdfOutput = $dompdf->output();

    // Return PDF response
    return new Response($pdfOutput, Response::HTTP_OK, [
        'Content-Type' => 'application/pdf',
        'pdfContent' => base64_encode($pdfOutput),
    ]);
}
    
        #[Route('/showdocuser', name: 'showdocuser')] //affichage
        public function showdocuser(MedecinRepository $userRepository): Response
        {
    
            $user=$userRepository->findAll();
            return $this->render('user/showdocuser.html.twig', [
                'user'=>$user,
    
            ]);
        }
    
        #[Route('/showdoc', name: 'showdoc')] //affichage
        public function showdoc(MedecinRepository $userRepository): Response
        {
    
            $user=$userRepository->findAll();
            return $this->render('user/showdoc.html.twig', [
                'user'=>$user,
    
            ]);
        }
    
    
    
        #[Route('/deleteuser/{id}', name: 'deleteuser')]
        public function deleteUser($id, SessionInterface $session): Response
        {
            // The $id parameter is automatically resolved from the route parameters
            
            $userRepository = $this->getDoctrine()->getRepository(Medecin::class);
    
            // Find the user by ID
            $user = $userRepository->find($id);
    
            // Check if the user exists
            if (!$user) {
                throw $this->createNotFoundException('User not founddddd');
            }
    
            // Delete the user
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($user);
            $entityManager->flush();
    
            // Clear the session
            $session->invalidate();
    
            // Redirect to an appropriate page after deletion
            // For example, redirect to the user list page
            return $this->redirectToRoute('signup');
        }


        #[Route('/deleteuserad/{id}', name: 'deleteuserad')]
        public function admindeleteuser($id): Response
        {
            // Retrieve the user entity by ID
            $userRepository = $this->getDoctrine()->getRepository(Medecin::class);
            $user = $userRepository->find($id);

            if (!$user) {
                throw $this->createNotFoundException('User not found');
            }
    
            // Remove the user entity
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($user);
            $entityManager->flush();
    
            // Add a flash message to notify the admin
            $this->addFlash('success', 'User deleted successfully');
    
            // Redirect to the page displaying the list of users
            return $this->redirectToRoute('showdbuser');
        }
        

        #[Route('/switchroleadmin/{id}', name: 'switchroleadmin')]
        public function switchUserRoleToAdmin($id, MedecinRepository $userRepository): Response
        {

templates/user/editdoc.html.twig
{# templates/user/profile.html.twig #}

{% extends 'form.html.twig' %}

{% block body %}

<div class="pagetitle">
      <h1>Profile</h1>
      <nav>
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="index.html">Home</a></li>
          <li class="breadcrumb-item">Users</li>
          <li class="breadcrumb-item active">Profile</li>
        </ol>
      </nav>
    </div>
    <section class="section profile">
      <div class="row">
        <div class="col-xl-4">

          <div class="card">
            <div class="card-body profile-card pt-4 d-flex flex-column align-items-center">
                {% if app.user is not null and app.user.photo is not null %}
              <img src="{{ asset('uploads/photos/' ~ app.user.photo) }}" alt="Profile" class="rounded-circle">
              <h2>{{ app.user.fullname }}</h2>
              <h3>{{ app.user.roles[0] }}</h3>
              <div class="social-links mt-2">
                <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
                <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
                <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
                <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></a>
              </div>
            </div>
          </div>

        </div>
        {% else %}
        <p>No profile photo available</p>
    {% endif %}
        <div class="col-xl-8">

          <div class="card">
            <div class="card-body pt-3">
              <!-- Bordered Tabs -->
              <ul class="nav nav-tabs nav-tabs-bordered" role="tablist">

                <li class="nav-item" role="presentation">
                  <a class="nav-link" href="{{path('profile')}}" role="tab" tabindex="-1">OverView</a>
              </li>

                <li class="nav-item" role="presentation">
                  <button class="nav-link" data-bs-toggle="tab" data-bs-target="#profile-edit" aria-selected="false" role="tab" tabindex="-1">Edit Profile</button>
                </li>

            
              <div class="tab-content pt-2">

              <br>
              <br>

                <div class="tab-pane fade profile-edit pt-3 active show" id="profile-edit" role="tabpanel">

                  <!-- Profile Edit Form -->
                  {{ form_start(form,{attr:{novalidate:'novalidate'}}) }}
                    <div class="row mb-3">
                      <label for="profileImage" class="col-md-4 col-lg-3 col-form-label">Profile Image</label>
                      <div class="col-md-8 col-lg-9">
                        {% if app.user is not null and app.user.photo is not null %}
                        <img src="{{ asset('uploads/photos/' ~ app.user.photo) }}"  alt="Profile" style="width: 120px; height:120px; border-radius: 50%;">
                        {% else %}
                              <p>No profile photo available</p>
                          {% endif %}
                      
                                
                          
                        </div>
                      </div>
                    </div>
                  
                    <div class="row mb-3">
                      <label for="fullName" class="col-md-4 col-lg-5 col-form-label">User Name</label>
                      <div class="col-md-8 col-lg-9">
                        {{ form_widget (form.username, {'attr': {'class': 'form-control'}}) }}
                        {{ form_errors (form.username, {'attr': {'class': 'form-danger'}}) }}
                      </div>
                    </div>
                    <div class="row mb-3">
                      <label for="fullName" class="col-md-4 col-lg-5 col-form-label">Full Name</label>
                      <div class="col-md-8 col-lg-9">
                        {{ form_widget (form.fullname, {'attr': {'class': 'form-control'}}) }}
                        {{ form_errors (form.fullname, {'attr': {'class': 'form-danger'}}) }}
                      </div>
                    </div>
                    <div class="row mb-3">
                      <label for="about" class="col-md-4 col-lg-5 col-form-label">Email</label>
                      <div class="col-md-8 col-lg-9">
                        {{ form_widget(form.email, {'attr': {'class': 'form-control'}}) }}
                        {{ form_errors (form.email, {'attr': {'class': 'form-danger'}}) }}
                      </div>
                    </div>

                    <div class="row mb-3">
                      <label for="company" class="col-md-4 col-lg-5 col-form-label">Phone Number</label>
                      <div class="col-md-8 col-lg-9">
                        {{ form_widget(form.phone, {'attr': {'class': 'form-control'}}) }}
                        {{ form_errors (form.phone, {'attr': {'class': 'form-danger'}}) }}
                      </div>
                    </div>
                    <div class="row mb-3">
                        <label for="company" class="col-md-4 col-lg-5 col-form-label">Speciality</label>
                        <div class="col-md-8 col-lg-9">
                          {{ form_widget(form.specialite, {'attr': {'class': 'form-control'}}) }}
                          {{ form_errors (form.specialite, {'attr': {'class': 'form-danger'}}) }}
                        </div>
                      </div>
                      <div class="row mb-3">
                        <label for="company" class="col-md-4 col-lg-5 col-form-label">Adress</label>
                        <div class="col-md-8 col-lg-9">
                          {{ form_widget(form.adress, {'attr': {'class': 'form-control'}}) }}
                          {{ form_errors (form.adress, {'attr': {'class': 'form-danger'}}) }}
                        </div>
                      </div>
                    <div class="row mb-3">
                      <label for="Job" class="col-md-4 col-lg-5 col-form-label">Password</label>
                      <div class="col-md-8 col-lg-9">
                        {{ form_widget(form.password.first, {'attr': {'class': 'form-control'}}) }}
                    {{ form_errors (form.password.first, {'attr': {'class': 'form-danger'}}) }}
                 
                      </div>
                    </div>

                    <div class="row mb-3">
                      <label for="Country" class="col-md-4 col-lg-5 col-form-label">Confirm Password</label>
                      <div class="col-md-8 col-lg-9">
                        {{ form_widget(form.password.second, {'attr': {'class': 'form-control'}}) }}
                        {{ form_errors (form.password.second, {'attr': {'class': 'form-danger'}}) }}
                      </div>
                    </div>

                    <div class="row mb-3">
                      <label for="Country" class="col-md-4 col-lg-5 col-form-label">Upload photo</label>
                      <div class="col-md-8 col-lg-9">
                        {{ form_widget(form.photo, {'attr': {'class': 'form-control'}}) }}
                       
                      </div>
                    </div>

                   

                    

                   

                    

                   


                    <div class="text-center">
                      
                      {{ form_widget(form.Submit, {'attr': {'class': 'btn btn-primary'}}) }}
                    </div>
                    {{ form_end(form) }}
                    <!-- End Profile Edit Form -->

                </div>
                <div class="tab-pane fade pt-3" id="profile-settings" role="tabpanel">

                  <!-- Settings Form -->
                  <form>

                    <div class="row mb-3">
                      <label for="fullName" class="col-md-4 col-lg-3 col-form-label">Email Notifications</label>
                      <div class="col-md-8 col-lg-9">
                        <div class="form-check">
                          <input class="form-check-input" type="checkbox" id="changesMade" checked="">
                          <label class="form-check-label" for="changesMade">
                            Changes made to your account
                          </label>
                        </div>
                        <div class="form-check">
                          <input class="form-check-input" type="checkbox" id="newProducts" checked="">
                          <label class="form-check-label" for="newProducts">
                            Information on new products and services
                          </label>
                        </div>
                        <div class="form-check">
                          <input class="form-check-input" type="checkbox" id="proOffers">
                          <label class="form-check-label" for="proOffers">
                            Marketing and promo offers
                          </label>
                        </div>
                        <div class="form-check">
                          <input class="form-check-input" type="checkbox" id="securityNotify" checked="" disabled="">
                          <label class="form-check-label" for="securityNotify">
                            Security alerts
                          </label>
                        </div>
                      </div>
                    </div>

                    <div class="text-center">
                      <button type="submit" class="btn btn-primary">Save Changes</button>
                    </div>
                  </form><!-- End settings Form -->

                </div>

                <div class="tab-pane fade pt-3" id="profile-change-password" role="tabpanel">
                  <!-- Change Password Form -->
                  

                </div>

              </div><!-- End Bordered Tabs -->

            </div>
          </div>

        </div>
      </div>
    </section>

{% endblock %}

templates/user/pdfadmin.html.twig
<table class="table datatable">
    <thead>
        <tr>
            <th>Id</th>
            <th>Username</th>
            <th>Fullname</th>
            <th>Email</th>
            <th>Role</th>
            <th>Photo</th>
        </tr>
    </thead>
    <tbody>
        {% for a in user %}
        <tr>
            <td>{{ a.id }}</td>
            <td>{{ a.username }}</td>
            <td>{{ a.fullname }}</td>
            <td>{{ a.email }}</td>
            {% if a.roles is not empty and 'user' in a.roles %}
            <td>{{ a.roles[0] }}</td>
            {% endif %}
            {% if a.photo is not empty %}
            <td><img src="{{ absolute_url(asset('uploads/photos/' ~ a.photo)) }}"></td>
{% else %}
No Photo
{% endif %}
        </tr>
        {% endfor %}
    </tbody>
</table>

<script>
    function toggleView() {
        var pdfSection = document.getElementById('pdfSection');
        var dataTablesSection = document.querySelector('.section');

        if (pdfSection.style.display === 'none') {
            pdfSection.style.display = 'block';
            dataTablesSection.style.display = 'none';
        } else {
            pdfSection.style.display = 'none';
            dataTablesSection.style.display = 'block';
        }
    }
</script>


<style>
    /* Style for table headers */
    table.datatable th {
        background-color: #f0f0f0; /* Light gray background */
        color: #333; /* Dark text color */
        padding: 10px; /* Padding around the content */
    }

    /* Style for table body */
    table.datatable td {
        border: 1px solid #ccc; /* Border around each cell */
        padding: 10px; /* Padding around the content */
    }

    /* Style for alternate rows */
    table.datatable tr:nth-child(even) {
        background-color: #f9f9f9; /* Lighter background color for even rows */
    }

    /* Style for odd rows */
    table.datatable tr:nth-child(odd) {
        background-color: #fff; /* White background color for odd rows */
    }
</style>

templates/user/showdocuser.html.twig
{% extends 'form.html.twig' %}

{% block body %}
<main id="main" class="main">

    <div class="pagetitle">
      <h1>Data Tables</h1>
      <nav>
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="index.html">Home</a></li>
          <li class="breadcrumb-item">Tables</li>
          <li class="breadcrumb-item active">Data</li>
        </ol>
      </nav>
    </div><!-- End Page Title -->

    <section class="section">
      <div class="row">
        <div class="col-lg-12">

          <div class="card">
            <div class="card-body">
            
              <h5 class="card-title">Datatables</h5>
            
              <!-- Table with stripped rows -->
              <table class="table datatable">
                
                <thead>
                  <tr>
                    <th>Id</th>
                    <th>Username</th>
                    <th>Fullname</th>
                    <th>Email</th>
                    
                    <th>Photo</th>
                    <th>Cancel Appoitment</th>
      
                  </tr>
                </thead>
                <tbody>
                  {%for a in user %}
                    {% if a.roles[0] =='user' %}
                  <tr>
                    <td>{{a.id}}</td>
                    <td>{{a.username}}</td> 
                    <td>{{a.fullname}}</td> 
                    <td>{{a.email}}</td>


  {% if a.photo is not empty %}
<td><img src="{{ asset('uploads/photos/' ~ a.photo) }}"  style="width: 80px; height: 80px; "></td>
{% else %}
No Role
{% endif %}
<td> <a class="btn btn-danger" href="" ><i class="fa-solid fa-ban fa-beat"></i></a></td>
                    </tr>
                    {% endif %}
                  {% endfor %}
                </tbody>
              </table>
              <!-- End Table with stripped rows -->

            </div>
          </div>

        </div>
      </div>
    </section>
  </main><!-- End #main -->
 <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

 
  {% endblock %}